from .lib import MultioException  # noqa: F401
from .metadata import Metadata  # noqa: F401
from .multio import Multio  # noqa: F401

try:
    # NOTE: the `version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"
